### ISSUE TITLE
consumer has goroutine leak for http persistConn readLoop and writeLoop after consumer.Close() called

### ISSUE THREAD

**Issue by goupeng212** [cloudfoundry/noaa#18] opened 2016-05-03 15:36 UTC
When I using noaa to consume firehose metrics data drain, I have to refresh the token as the token have to be expired for a period.
So the rough steps I used:
0.authToken = nozzle.authTokenFetcher.FetchAuthToken()
1. noaa.NewConsumer for the first time
2. get firehose metrics data via Consumer.FirehoseWithoutReconnect(authToken)
3. Time to refresh token, I close the ws via Consumer.Close()
At that time, I dumped the goroutines. I found the goroutine leaks on persistConn readLoop and writeLoop
goroutine 66 [select, 7 minutes]:
net/http.(*persistConn).readLoop(0xc8200cd1e0)
        /usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 67 [select, 7 minutes]:
net/http.(*persistConn).writeLoop(0xc8200cd1e0)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

**Comment by Jim-Campbell** [comment] 2016-05-03 15:40
What version of CF are you using?

**Comment by goupeng212** [comment] 2016-05-03 16:00
cf-226004

**Comment by goupeng212** [comment] 2016-05-03 16:09
Jim,
From my understanding, the consumer using http transport to re-use the connection to Traffic controller. However, the consumer.Close() don't have chance to set the reusable connection as idleconnection or any close connection operation.
I found the KeepAlive setting in the line 23, but never used.

**Comment by wfernandes** [comment] 2016-05-03 20:23
@goupeng212 We've deprecated `noaa.Consumer` (created with `noaa.NewConsumer`); Could you reproduce the issue with the consumer returned by [`consumer.New`](https://github.com/cloudfoundry/noaa/blob/master/consumer/consumer.go#L56-L67)?

**Comment by wfernandes** [comment] 2016-05-09 15:09
@goupeng212 Just wanted to check in. Were you able to reproduce the goroutine leak by using the new [`Consumer`](https://github.com/cloudfoundry/noaa/blob/master/consumer/consumer.go#L42-L54)?

**Comment by wfernandes** [comment] 2016-08-26 19:46
Closing this issue. Will reopen if there is evidence that leak is caused by the new Consumer.

**Closed by wfernandes** 2016-08-26 19:46 UTC
